### PR TITLE
Use Compat for 0.4 Tuple syntax

### PR DESCRIPTION
**Pull request by tkelman**
This depends on https://github.com/nolta/Winston.jl/pull/212 being merged and tagged

### CODE REVIEW

**Comment by timholy** [comment]
This is great. But why does it need to wait on Winston? Winston depends on this package, not the other way around.

**Comment by tkelman** [comment]
I suppose it doesn't. The tests depend on Winston, so it doesn't really matter which order things get done in.

**Comment by tkelman** [comment]
Does this package have a maintainer, or should I just merge this?

**Comment by timholy** [comment]
It does not have a maintainer. So go ahead.

**Comment by tkelman** [comment]
Ok thanks, that's about what I thought but good to confirm whether that was the case.

**Pull request merged**
