### PR TITLE
fixes for 0.4rc2

### PR DESCRIPTION
**Pull request by rened**
String -> AbstractString
Nothing -> Void
Union(...) -> Union{...}

### CODE REVIEW

**Comment by ivarne** [comment]
The travis testing looks strange. Can you look into it?

I'm also not sure if Compat.jl is able to make `Union{ ... }` work on 0.3 without a macro transformation. Can you test/verify (or update REQUIRE)?

**Comment by rened** [comment]
I think it would be good to leave 0.3 out. The failures for 0.4 come mainly from the dependencies, I am submitting PRs to those and will the retrigger this travis build.

**Comment by rened** [comment]
Now using `@compat` everywhere, 0.3 should work as well, let's wait for travis.

**Comment by rened** [comment]
Had to modify to checkout `Winston` master to make the tests pass. I can revert this before merging.

Also, OSX testing is not set up correctly and could never pass - I'll try to come up with a fix for this in a later PR.

**Comment by ivarne** [comment]
If supporting 0.3 is a hassle, I don't think it is important as long as we keep REQUIRE updated with the new requirements.

**Comment by rened** [comment]
ok - 0.3 works now, but we could deprecate it in a couple of weeks once 0.4 is settled in. Shall I revert the changes to .travis to make this merge-able?

**Comment by catawbasam** [comment]
bump?  Getting lots of warnings under 0.4.

**Comment by timholy** [comment]
I'll merge, and we can decide about the .travis.yml later (does one still need master on Winston?)

**Pull request merged**
