### PR TITLE
Add keywords for file dialogs

### PR DESCRIPTION
**Pull request by eshain**
I'm new at this so perhaps I'm doing this wrong. In any case I like the Tk file dialogs GetOpenFile(), GetSaveFile() and ChooseDirectory(), but currently Tk keywords aren't defined. I've endeavored to write more capable versions. I will say that I'm new at Julia and not a professional programmer in any case so these functions may not have the best syntax. I modeled them on the Messagebox syntax. They don't have the parent keyword defined so that might be an improvement. Here they are:

```jl
function GetOpenFile(;filetypes::Vector=String[], initialdir::String="",initialfile::String="", multiple::Bool=false,        title::String="")
  args = Dict()
  if length(filetypes) > 0 args["filetypes"] = filetypes end
  if length(initialdir) > 0 args["initialdir"] = initialdir end
  if length(initialfile) > 0 args["initialfile"] = initialfile end
  args["multiple"] = multiple
  if length(title) > 0 args["title"] = title end
  tcl("tk_getOpenFile", args)
end

function GetSaveFile(;filetypes::Vector=String[], initialdir::String="", initialfile::String="", title::String="")
  args = Dict()
  if length(filetypes) > 0 args["filetypes"] = filetypes end
  if length(initialdir) > 0 args["initialdir"] = initialdir end
  if length(initialfile) > 0 args["initialfile"] = initialfile end
  if length(title) > 0 args["title"] = title end
  tcl("tk_getSaveFile", args)
end

function ChooseDirectory(;initialdir::String="",mustexist=false,title::String="")
  args = Dict()
  if length(initialdir) > 0 args["initialdir"] = initialdir end
  if length(title) > 0 args["title"] = title end
  args["mustexist"] = mustexist
    tcl("tk_chooseDirectory", args)
end
```jl

### CODE REVIEW

**Comment by nalimilan** [comment]
I'm not sure what you did, but many unrelated commits are included in this branch, and your changes are apparently missing. The easiest solution is to create a new branch (or reset this one using `git reset --hard master` -- be careful this removes all local commits on the branch), rebase it against master, and apply the changes again. Mastering git and pull requests always takes some time...

**Comment by eshain** [comment]
I’m sorry, but your instructions make nearly no sense to me. Can you help me through this?

Eric

**Comment by eshain** [comment]
I believe I deleted my pull request. I’ve never used Git before and have no idea how to create the pull request correctly.

Eric

**Comment by nalimilan** [comment]
The problem is more with the branch than with the pull request. Typically, on creates a branch to make a pull request like this:
```
git checkout master
git pull # ensure the local branch is up to date
git checkout -b mybranch # create the new branch
[make your changes, commit, etc.]
git push eschain mybranch # push branch to GitHub fork
```
And then create a pull request on GitHub's web interface.

You probably master most of this process already since you created this PR. I don't know what went wrong.

**Comment by eshain** [comment]
I don't understand Git. I was hoping to just open a pull request and just suggest my code in the comments. 

- Eric

**Comment by nalimilan** [comment]
git is very powerful but also a bit scary at first. I think GitHub offers good tutorials, and the code I posted above should be all you need to make a pull request.

Else, you can just file an issue with your code in the description.

**Comment by eshain** [comment]
That is what I tried to do but I guess I found even that too complicated. 

- Eric

**Comment by timholy** [comment]
There's definitely a learning curve with git. That said, once you get over it, you'll wonder how you ever wrote code before.

So perhaps let's go back to the beginning:
- First, make a copy of any new code you've written in some other directory, because we're going to start from scratch. 
- From julia, do `Pkg.checkout("Tk")`. If it complains at you, drop to the command line and say `git checkout master`: it might complain that you have modifications. Use `git status` to check to see what's changed. You can say `git checkout <filename>` to discard any local changes in any files and go back to the version in this repository. Eventually you should get to the point where `git checkout master` works.
- In the worst-case scenario, just delete the entire `Tk` directory from inside your `.julia/v0.x` directory, and then do `Pkg.add("Tk")`. In a crisis, just delete your entire `.julia` directory, if you haven't made other changes you don't want to lose.

From that point, @nalimilan's instructions _should_ work. FYI for newcomers I find that `git gui` makes the whole process more friendly. After you've changed the code, just type `git gui` on the command line. You'll see files you've changed in the upper left; you can browse them to see what you've changed, and whether you've left any unintended changes in. Once you're ready to commit, click on the icon (not the filename) and they will move down to the "staged changes" area. In the commit message box, type your summary of the change and then click "Commit." Finally, go back to julia and type `Pkg.submit("Tk")`.

**Comment by eshain** [comment]
Tim,

I can do Pkg.checkout(“Tk”) but from there it just isn’t clear what to do. Am I using git from Terminal or within Julia? @nallmilan’s instructions really aren’t clear to me. Do I type the commands exactly as he says or do I need to specify Tk? Were do the files go and which file should I edit. I assume it is the dialogs.jl. See questions below in after the “##".

git checkout master  ## Do I do this in addition to the Pkg.checkout(“Tk”)? Do I need to be in the Tk directory?
git pull # ensure the local branch is up to date
git checkout -b mybranch # create the new branch ## Where does this mybranch go?
[make your changes, commit, etc.] ## What do you mean by commit, etc. Am I editing the dialogs.jl file in the Tk/src folder?
git push eschain mybranch # push branch to GitHub fork ## I assume he means “eshain”. Do I also do some sort of Pkg.checkin() in Jula?

Thanks
Eric

**Comment by eshain** [comment]
Tim,

By the way, git gui doesn’t do anything, but there is a git client for OS X and I’ve installed and opened it.

Eric

**Comment by eshain** [comment]
I used the GitHub application to clone the Tk package, make my changes and commit/sync. I’m wondering if this is all I need to do?

Eric

**Comment by timholy** [comment]
Great! You're definitely making progress.

Forking the package on GitHub was a fine thing to do, but `Pkg.submit("Tk")` would also have done that automatically for you. (It's also happy to work with a pre-existing fork, so don't worry, you didn't mess anything up.)

It might be helpful to conceptualize things this way:
- You want to make changes to some code, but you don't "own" it so you don't have write permissions
- You can edit the corresponding code on your own machine, but no one else can see what's on your machine. So there is no way to share it with the world.
- Strategy: use an intermediary repository, which is your own personal GitHub fork of Tk.jl. The key point is that you have "write" access to this repository (so you can push changes from your machine to it), and the rest of the world has "read" access to it (it's up on the web and does not need a password to view the content). After you push code up to your fork, then you submit a "pull request" from your fork to the main Tk.jl repository: this is a request to merge the changes in your fork into the main repository.

I've realized our documentation on this topic is just not good enough. I submitted https://github.com/JuliaLang/julia/pull/10367; the sections I added can be viewed (though the hyperlinks won't work) here:
https://github.com/JuliaLang/julia/blob/43abffe63c1eaab2ba6682a3d81c3bb2316e6f97/doc/manual/packages.rst#making-changes-to-an-existing-package

Let me know whether this clarifies matters, and especially if you find some steps still confusing.

**Comment by eshain** [comment]
Tim,

You have to make sure it goes back to square one. For instance I needed to register with GitHub and then do a sign in of sorts in Git. What I was unclear of was how to create a new repository and where that was. The GitHub app made that very easy. 

- Eric

**Comment by timholy** [comment]
All that's described in the section right above the one I linked to (sorry, I just started at the new material).

But I made some additional changes. The latest (starting at the whole section) is here: https://github.com/JuliaLang/julia/blob/0c0cb5d56e297eee5478e2857585432953535c0b/doc/manual/packages.rst#package-development

**Comment by eshain** [comment]
Tim,

Thanks. The document link is helpful. I’m still unclear about creating a new branch and where that resides on my computer. I’m assuming it is a separate directory somewhere, but perhaps not? In the mean time I very much appreciate the help. This will be my very first contribution to an open source project (as minimal as it seems).

I am interested in how you approach development. I don’t really get Juno as it doesn’t really have a REPL console. Also I’m finding debugging a challenge compared to working in MATLAB’s IDE. I’m on a Mac and generally use TextWrangler for Python stuff. TextWrangler doesn’t seem to understand Julia yet so it isn’t quite as helpful about syntax highlighting, etc.

Eric


- Eric

**Comment by timholy** [comment]
No, it's in the same directory as the package itself. There's a hidden `.git` directory that keeps track of all the state for git.

Since you seem interested in understanding how it all works (rather than just following the cookbook), I highly recommend the **outstanding** http://git-scm.com/doc. Most of the material in chapters 1, 2, and the first half of 3 is pretty dang useful. Some years ago I spent some time trying to contribute to an open-source project without really learning git; it got more enjoyable once I cleared 2 hours from my schedule, made myself a cup of tea, and just started reading, working my way carefully through all the diagrams to really understand what was happening. Once you get the basic ideas, it's an amazing tool.

I actually intend to make myself use Juno for a week, because it does seem powerful (I got started with Julia before Juno existed, and have been lazy about changing my ways). I just use a text editor (Kate) and use a workflow similar to http://docs.julialang.org/en/latest/manual/workflow-tips/.

**Pull request closed without merging**
